### PR TITLE
chore: update performace & simplified code

### PR DESCRIPTION
**Pull request by Spyei**

### CODE REVIEW

**Comment by nexusprime-here** [comment]
Looks great!

**Comment by nexusprime-here** [comment]
change `name: string = 'World'` to `name?: string`

@Spyei

**Comment by Spyei** [comment]
already fixed this.

**Comment by byvide** [comment]
1. Ensure that you run formatting locally (`deno fmt`), and optionally, perform other checks and tests as well.
2. The current change will fail the tests as it doesn't consider the use of strings with whitespaces. While this is a demo package with a simple "hello world" function, it's important to consider this aspect for best practices and to be mindful of potential vulnerabilities in real projects.
3. If you claim performance improvement, back it up. This is a great opportunity to use the Deno API. I have already done so, and the correct implementation of this change is indeed significant. You can verify it with `deno bench` after updating your fork.
4. Don't neglect the JSDoc when changing the characteristics of the function.
5. Thank you for your contribution.

**Comment by byvide** [comment]
@Spyei 
I apologize if there was any miscommunication. I did benchmark your suggestions but didn't update the source code to avoid taking credit for your work. Are you planning to implement the changes?

**Comment by byvide** [comment]
Implemented.

**Pull request closed without merging**
